danieltj_memberreputation_like_post_controller:
    path: /reputation/{post_id}/like
    defaults: { _controller: danieltj.memberreputation.like_post:like }
    requirements:
        post_id: \d+

danieltj_memberreputation_dislike_post_controller:
    path: /reputation/{post_id}/dislike
    defaults: { _controller: danieltj.memberreputation.dislike_post:dislike }
    requirements:
        post_id: \d+
